# Generated by Django 4.0.4 on 2022-05-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_game_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_of_players',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(),
        ),
    ]
